import test from 'node:test';
import assert from 'node:assert/strict';
import { selectCommissionRule, commissionBreakdown, assertSettlementCurrency } from '../rpe-v2/supabase/functions/_shared/commission.ts';
const global={id:'global',active:true,effective_from:'2026-01-01',effective_to:null,rule_version:1,currency:'GHS',commission_rate:0,payment_processing_rate:0,payment_fixed_fee:0,payment_fee_payer:'platform'};
const ctx={store_id:'store',seller_country_code:'GH',buyer_country_code:'GH',payment_method:'Mobile Money',currency:'GHS'};
const gh={...global,id:'gh',seller_country_code:'GH',buyer_country_code:'GH',commission_rate:5};
test('Ghana policy wins over global fallback',()=>assert.equal(selectCommissionRule([global,gh],ctx).id,'gh'));
test('another buyer country uses configured fallback, not Ghana rate',()=>assert.equal(selectCommissionRule([global,gh],{...ctx,buyer_country_code:'NG'}).id,'global'));
test('store-specific contract wins over country rule',()=>assert.equal(selectCommissionRule([gh,{...global,id:'store-policy',store_id:'store'}],ctx).id,'store-policy'));
test('expired, inactive, future and wrong-currency rules cannot match',()=>{const ignored=[{...gh,active:false},{...gh,effective_to:'2026-02-01'},{...gh,effective_from:'2099-01-01'},{...gh,currency:'USD'}];assert.equal(selectCommissionRule([global,...ignored],ctx).id,'global')});
test('no applicable rule fails instead of silently using zero commission',()=>assert.throws(()=>selectCommissionRule([],ctx),/No active/));
test('unsupported currency is never relabelled as GHS',()=>assert.throws(()=>assertSettlementCurrency('NGN'),/settles in GHS/));
test('5% of 600 is 30; delivery belongs to seller',()=>{const b=commissionBreakdown(gh,600,50);assert.equal(b.commission_amount,30);assert.equal(b.seller_payout_estimate,620);assert.equal(b.buyer_total_estimate,650)});
test('platform absorbs separate provider fee',()=>{const b=commissionBreakdown({...gh,payment_processing_rate:2},600,0);assert.equal(b.seller_payout_estimate,570);assert.equal(b.platform_net_before_other_costs,18);assert.equal(b.buyer_total_estimate,600)});
test('seller-paid provider fee is deducted once',()=>{const b=commissionBreakdown({...gh,payment_processing_rate:2,payment_fee_payer:'seller'},600,0);assert.equal(b.seller_payout_estimate,558);assert.equal(b.platform_net_before_other_costs,30)});
test('buyer-paid provider fee is disclosed separately',()=>{const b=commissionBreakdown({...gh,payment_processing_rate:2,payment_fee_payer:'buyer'},600,0);assert.equal(b.seller_payout_estimate,570);assert.equal(b.buyer_total_estimate,612)});
test('rounding is at the cent boundary',()=>assert.equal(commissionBreakdown(gh,.10).commission_amount,.01));
test('invalid rates and negative payouts rejected',()=>{assert.throws(()=>commissionBreakdown({...gh,commission_rate:101},100));assert.throws(()=>commissionBreakdown({...gh,payment_fixed_fee:500,payment_fee_payer:'seller'},100),/negative/);assert.throws(()=>commissionBreakdown(gh,-1));assert.throws(()=>commissionBreakdown(gh,''))});
test('provider costs can exceed commission and are shown as a loss',()=>assert.equal(commissionBreakdown({...gh,payment_processing_rate:6},100).platform_net_before_other_costs,-1));
