(()=>{
'use strict';
const cfg=window.RPE_CONFIG||{},root=document.getElementById('marketApp'),overlay=document.getElementById('marketOverlay');
const $=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=cfg.supabaseUrl&&cfg.supabasePublishableKey&&window.supabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
window.RPE_SUPABASE=db;
const KEY='ranova_market_cart_v2',DEVICE='ranova_market_device_v1',BATCH=24;
let quoteSequence=0,lastOrderPhone='',items=[],stores=new Map(),cart={},shown=BATCH,category='',query='',storeId='',nonce=0,loading=false,session=null,sortMode='recommended',maxMinimum=0,pricedOnly=false,compareIds=[];
try{cart=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{cart={}}
let device='';try{device=localStorage.getItem(DEVICE)||crypto.randomUUID();localStorage.setItem(DEVICE,device)}catch{device=String(Math.random())}
const money=(v,c='GHS')=>v==null?'Ask for price':new Intl.NumberFormat('en-GH',{style:'currency',currency:c||'GHS'}).format(Number(v));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const img=p=>p.image||'';
const available=p=>p.stock_status!=='out_of_stock'&&(p.stock_quantity==null||Number(p.stock_quantity)>=Number(p.moq||1));
const tierPrice=(p,q)=>{let value=p.price==null?null:Number(p.price);for(const t of (p.pricing_tiers||[]).slice().sort((a,b)=>Number(a.min_qty)-Number(b.min_qty)))if(q>=Number(t.min_qty||0)&&Number.isFinite(Number(t.unit_price)))value=Number(t.unit_price);return value};
const seed=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
function shuffle(a,s){let arr=[...a],v=seed(s);for(let i=arr.length-1;i>0;i--){v+=0x6d2b79f5;let t=v;t=Math.imul(t^t>>>15,1|t);t^=t+Math.imul(t^t>>>7,61|t);let j=Math.floor(((t^t>>>14)>>>0)/4294967296*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function fairOrder(a){let buckets=new Map(),ordered=[];for(const p of shuffle(a,device+'|'+Math.floor(Date.now()/600000)+'|'+nonce)){if(!buckets.has(p.store_id))buckets.set(p.store_id,[]);buckets.get(p.store_id).push(p)}let keys=shuffle([...buckets.keys()],device+'|stores|'+nonce);while(keys.length){let next=[];for(const k of keys){let b=buckets.get(k);ordered.push(b.shift());if(b.length)next.push(k)}keys=shuffle(next,device+'|round|'+ordered.length)}return ordered}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(cart))}catch{}updateCount()}
function updateCount(){let n=Object.values(cart).reduce((s,q)=>s+Number(q||0),0);$('marketCartCount').textContent=n||''}
function note(t){$('marketGrid').innerHTML='<p class="market-state">'+safe(t)+'</p>'}
function canonical(rows){const seen=new Set();return rows.filter(p=>{let key=p.store_id+'|'+norm(p.name);if(seen.has(key))return false;seen.add(key);return true})}
async function load(){if(!db){note('The product catalogue is temporarily unavailable.');return}loading=true;note('Loading products from RANOVA stores…');try{
 const [sellers,sp,core]=await Promise.all([
 db.from('ranova_seller_stores').select('id,store_name,slug,tagline,description,logo_url,business_location,fulfilment_summary,return_policy_summary').eq('store_status','active').limit(500),
 db.from('ranova_seller_products').select('id,store_id,name,category,short_description,description,price,currency,moq,stock_quantity,stock_status,unit_label,primary_image_url,image_urls,pricing_tiers,created_at').eq('product_status','active').order('created_at',{ascending:false}).limit(1000),
 db.from('products').select('id,name,sku,legacy_id,short_description,description,price,currency,stock_quantity,stock_status,specifications,product_images(image_url,is_primary,sort_order),categories(name)').eq('active',true).limit(1000)
 ]);
 if(sellers.error||sp.error||core.error)throw new Error('Could not load the catalogue. Tap Refresh to try again.');
 stores=new Map((sellers.data||[]).map(s=>[s.id,s]));const prime={id:'ranova-prime',store_name:'Ranova Prime Enterprise',description:'Official RANOVA Prime catalogue',business_location:'Ghana'};stores.set(prime.id,prime);
 const seller=(sp.data||[]).filter(p=>stores.has(p.store_id)&&p.stock_status!=='out_of_stock').map(p=>({...p,kind:'seller',image:p.primary_image_url||p.image_urls?.[0]||'',store_name:stores.get(p.store_id).store_name,images:[p.primary_image_url,...(p.image_urls||[])].filter(Boolean)}));
 const known=new Set(seller.filter(p=>/ranova prime/i.test(p.store_name)).map(p=>norm(p.name)));
 const legacy=(core.data||[]).filter(p=>p.stock_status!=='out_of_stock'&&!known.has(norm(p.name))).map(p=>{let images=(p.product_images||[]).slice().sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||(a.sort_order||0)-(b.sort_order||0)).map(x=>x.image_url);return {...p,store_id:prime.id,store_name:prime.store_name,kind:'prime',category:p.categories?.name||'Other',moq:1,image:images[0]||'',images}});
 items=canonical([...seller,...legacy]);if(!items.length)note('No approved products are available yet. Check again shortly.');else render();
 }catch(e){note(e.message||'Could not load products. Tap Refresh to retry.')}finally{loading=false}}
function filtered(){let a=items;if(storeId)a=a.filter(p=>p.store_id===storeId);if(category)a=a.filter(p=>p.category===category);if(query){const q=norm(query);a=a.filter(p=>norm([p.name,p.category,p.description,p.short_description,p.store_name].join(' ')).includes(q))}if(maxMinimum)a=a.filter(p=>Number(p.moq||1)<=maxMinimum);if(pricedOnly)a=a.filter(p=>tierPrice(p,Number(p.moq||1))!=null);if(sortMode==='price')return [...a].sort((x,y)=>{const px=tierPrice(x,Number(x.moq||1)),py=tierPrice(y,Number(y.moq||1));return (px==null)-(py==null)||String(x.currency||'GHS').localeCompare(String(y.currency||'GHS'))||(px??Infinity)-(py??Infinity)||x.name.localeCompare(y.name)});if(sortMode==='newest')return [...a].sort((x,y)=>String(y.created_at||'').localeCompare(String(x.created_at||''))||x.name.localeCompare(y.name));return query||category||storeId?a:fairOrder(a)}
function card(p){let disabled=!available(p),selected=compareIds.includes(String(p.id)),picture=img(p)?'<img src="'+safe(img(p))+'" alt="'+safe(p.name)+'" loading="lazy">':'<span class="market-state">Image unavailable</span>';return '<article class="market-card"><button class="market-image" data-product="'+safe(p.id)+'" aria-label="View '+safe(p.name)+'">'+picture+'</button><div class="market-card-body"><button class="market-store-link" data-store="'+safe(p.store_id)+'">'+safe(p.store_name)+'</button><button class="market-name" data-product="'+safe(p.id)+'">'+safe(p.name)+'</button><div class="market-meta">'+safe(p.category||'Product')+' · Min '+Number(p.moq||1)+'</div><div class="market-price">'+safe(money(tierPrice(p,Number(p.moq||1)),p.currency))+'</div></div><div class="market-card-actions"><button class="market-add" data-add="'+safe(p.id)+'" '+(disabled?'disabled':'')+'>'+(disabled?'Unavailable':'Add to cart')+'</button><button class="market-compare '+(selected?'selected':'')+'" data-compare="'+safe(p.id)+'" aria-pressed="'+selected+'">'+(selected?'✓ Selected':'Compare')+'</button></div></article>'}
function render(){const a=filtered();$('marketHeading').textContent=storeId?(stores.get(storeId)?.store_name||'Store'):query?('Results for “'+query+'”'):category||'Discover products';$('marketGrid').innerHTML=a.length?a.slice(0,shown).map(card).join(''):'<p class="market-state">No products match these choices. Try another search, quantity, or price filter.</p>';$('marketMore').classList.toggle('hide',a.length<=shown);const cats=[...new Set(items.map(p=>p.category).filter(Boolean))].sort();$('marketCategories').innerHTML=['All',...cats].map(c=>'<button type="button" data-category="'+safe(c==='All'?'':c)+'" class="'+(category===(c==='All'?'':c)?'selected':'')+'">'+safe(c)+'</button>').join('');$('marketStoreView').classList.toggle('hide',!storeId);if(storeId){const s=stores.get(storeId);$('marketStoreView').innerHTML='<button class="market-back" data-back>← All stores</button><div class="market-store-head">'+(s?.logo_url?'<img src="'+safe(s.logo_url)+'" alt="">':'')+'<div><h1>'+safe(s?.store_name||'Store')+'</h1><p>'+safe(s?.business_location||'')+'</p></div></div><p>'+safe(s?.description||s?.tagline||'Browse this store’s products.')+'</p>'+(s?.fulfilment_summary?'<p><b>Delivery:</b> '+safe(s.fulfilment_summary)+'</p>':'')+(s?.return_policy_summary?'<p><b>Returns:</b> '+safe(s.return_policy_summary)+'</p>':'')}renderCompareTray()}
function renderCompareTray(){compareIds=compareIds.filter(id=>items.some(p=>String(p.id)===id));const tray=$('marketCompareTray');tray.classList.toggle('hide',!compareIds.length);tray.innerHTML=compareIds.length?'<span>'+compareIds.length+' of 3 selected for comparison</span><button type="button" data-open-compare '+(compareIds.length<2?'disabled':'')+'>Compare products</button><button type="button" data-clear-compare>Clear</button>':''}
function toggleCompare(id){id=String(id);if(compareIds.includes(id))compareIds=compareIds.filter(x=>x!==id);else if(compareIds.length<3)compareIds.push(id);else{alert('You can compare up to 3 products. Remove one first.');return}render()}
function showCompare(){let selected=compareIds.map(id=>items.find(p=>String(p.id)===id)).filter(Boolean);if(selected.length<2)return;let row=(label,value)=>'<tr><th scope="row">'+safe(label)+'</th>'+selected.map(p=>'<td>'+value(p)+'</td>').join('')+'</tr>';openSheet('Compare products','<p class="market-note">Prices shown are for each product’s minimum order quantity. Delivery and final charges are confirmed during checkout.</p><div class="market-compare-scroll"><table class="market-compare-table"><thead><tr><th scope="col">Details</th>'+selected.map(p=>'<th scope="col">'+(p.image?'<img src="'+safe(p.image)+'" alt="">':'')+'<button data-product="'+safe(p.id)+'">'+safe(p.name)+'</button></th>').join('')+'</tr></thead><tbody>'+row('Seller',p=>safe(p.store_name))+row('Category',p=>safe(p.category||'Not listed'))+row('Unit price at minimum order',p=>safe(money(tierPrice(p,Number(p.moq||1)),p.currency)))+row('Minimum order',p=>Number(p.moq||1)+' '+safe(p.unit_label||'items'))+row('Available quantity',p=>p.stock_quantity==null?'Ask seller':Number(p.stock_quantity)+' '+safe(p.unit_label||'items'))+row('Action',p=>'<button class="market-compare-add" data-add="'+safe(p.id)+'" '+(!available(p)?'disabled':'')+'>Add to cart</button>')+'</tbody></table></div>')}
function openSheet(title,body){overlay.innerHTML='<div class="market-sheet"><div class="market-sheet-head"><h2>'+safe(title)+'</h2><button type="button" data-close aria-label="Close">×</button></div>'+body+'</div>';overlay.classList.remove('hide');document.body.style.overflow='hidden'}
function closeSheet(){overlay.classList.add('hide');overlay.innerHTML='';document.body.style.overflow=''}
function product(id){const p=items.find(x=>x.id===id);if(!p)return;let images=[...new Set(p.images||[])];openSheet(p.name,'<div class="market-gallery">'+(images.length?images.map(x=>'<img src="'+safe(x)+'" alt="'+safe(p.name)+'">').join(''):'<p>Image unavailable</p>')+'</div><h3>'+safe(p.name)+'</h3><button class="market-store-link" data-store="'+safe(p.store_id)+'">Sold by '+safe(p.store_name)+'</button><div class="market-detail-row"><b>'+safe(money(tierPrice(p,Number(p.moq||1)),p.currency))+' per '+safe(p.unit_label||'item')+'</b><small>Minimum order: '+Number(p.moq||1)+' · '+safe(p.stock_status?.replaceAll('_',' ')||'Confirm availability')+(p.stock_quantity!=null?' · Up to '+Number(p.stock_quantity)+' available':'')+'</small></div><p class="market-description">'+safe(p.description||p.short_description||'Ask the seller for more details before ordering.')+'</p>'+(p.pricing_tiers?.length?'<div class="market-tier-list"><b>Quantity prices</b>'+p.pricing_tiers.slice().sort((a,b)=>Number(a.min_qty)-Number(b.min_qty)).map(t=>'<div><span>'+Number(t.min_qty)+'+ '+safe(p.unit_label||'items')+'</span><strong>'+safe(money(t.unit_price,p.currency))+' each</strong></div>').join('')+'</div>':'')+(p.specifications?Object.entries(p.specifications).map(([k,v])=>'<div class="market-detail-row"><b>'+safe(k.replaceAll('_',' '))+'</b><small>'+safe(typeof v==='object'?JSON.stringify(v):v)+'</small></div>').join(''):'')+'<button class="market-primary" data-add="'+safe(p.id)+'" '+(!available(p)?'disabled':'')+'>'+(available(p)?'Add to cart':'Unavailable')+'</button>')}
function add(id){let p=items.find(x=>x.id===id);if(!p||!available(p))return;cart[id]=Math.max(Number(p.moq||1),Number(cart[id]||0)+1);if(p.stock_quantity!=null)cart[id]=Math.min(cart[id],Number(p.stock_quantity));persist();showCart()}
function cartLines(){let valid=Object.entries(cart).map(([id,q])=>({p:items.find(x=>x.id===id),q:Number(q)})).filter(x=>x.p&&x.q>0);return valid}
function showCart(){let a=cartLines();openSheet('Your cart',a.length?a.map(({p,q})=>'<div class="market-cart-row">'+(p.image?'<img src="'+safe(p.image)+'" alt="">':'<span></span>')+'<div><b>'+safe(p.name)+'</b><small>'+safe(p.store_name)+' · '+safe(money(tierPrice(p,q),p.currency))+' each'+(p.price==null&&!p.pricing_tiers?.length?' · quote needed':'')+'</small><div class="market-qty"><button data-quantity="'+safe(p.id)+'" data-step="-1" aria-label="Decrease quantity">−</button><span>'+q+'</span><button data-quantity="'+safe(p.id)+'" data-step="1" aria-label="Increase quantity">+</button></div></div><button class="market-remove" data-remove="'+safe(p.id)+'">Remove</button></div>').join('')+'<div id="marketCartQuote" class="market-quote">Checking current prices and availability…</div><p class="market-note">Delivery is calculated per store. Unconfirmed prices are quoted before payment.</p><button class="market-primary" data-checkout disabled>Place order</button>':'<p class="market-note">Your cart is empty. Browse products and add the ones you want.</p>');if(a.length)updateQuote('GH','marketCartQuote')}
window.RPE_MARKET_CART=()=>{window.RPE_OPEN_MARKET();showCart()};
window.RPE_MARKET_ADD=(id,name)=>{const p=items.find(x=>x.id===id)||items.find(x=>/ranova prime/i.test(x.store_name)&&norm(x.name)===norm(name));if(!p){window.RPE_OPEN_MARKET();$('marketSearch').value=name||'';query=name||'';render();return false}window.RPE_OPEN_MARKET();add(p.id);return true};
async function getQuote(country){
 const lines=cartLines().filter(({p})=>p.kind==='seller');
 if(!lines.length)return {ok:true,groups:[],product_total:null,all_prices_known:false};
 const res=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-cart-quote',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1','apikey':cfg.supabasePublishableKey},body:JSON.stringify({buyer_country_code:country,items:lines.map(({p,q})=>({product_id:p.id,quantity:q}))})});
 const out=await res.json();if(!res.ok||!out.ok)throw Error(out.error||'Could not check the cart.');
 const present=new Set((out.groups||[]).flatMap(g=>g.items.map(i=>i.product_id)));
 out.unavailable=lines.some(({p})=>!present.has(p.id))||(out.groups||[]).some(g=>['restricted','suspended'].includes(g.enforcement_status)||g.items.some(i=>!i.available||i.stock_shortage));
 return out;
}
function quoteHtml(out){let legacy=cartLines().filter(({p})=>p.kind!=='seller');return (out.groups||[]).map(g=>'<div class="market-quote-store"><b>'+safe(g.store_name)+'</b>'+g.items.map(i=>'<div><span>'+safe(i.name)+' × '+Number(i.quantity)+'</span><strong>'+safe(money(i.line_total))+'</strong></div>'+(i.available?'':'<small class="market-alert">Unavailable at this quantity. Reduce or remove it.</small>')).join('')+(g.delivery_options?.length?'<small>Delivery options: '+safe(g.delivery_options.map(z=>z.zone_name+' ('+(z.pricing_type==='fixed'?money(z.fixed_fee,z.currency):z.pricing_type)+')').join(', '))+'</small>':'<small>Delivery fee is confirmed separately.</small>')+'</div>').join('')+(legacy.length?'<div class="market-quote-store"><b>RANOVA catalogue</b><small>'+legacy.length+' item(s) need a confirmed price before payment.</small></div>':'')+'<div class="market-total">'+((!legacy.length&&out.all_prices_known)?'Product total: '+safe(money(out.product_total)):'Product total: Confirmed before payment')+'</div>'+(out.unavailable?'<p class="market-alert">An item is no longer available. Update your cart before ordering.</p>':'');}
async function updateQuote(country,target){const id=++quoteSequence,el=$(target);if(!el)return;el.textContent='Checking current prices and availability…';try{const out=await getQuote(country);if(id!==quoteSequence||!$(target))return;$(target).innerHTML=quoteHtml(out);const button=overlay.querySelector(target==='marketCartQuote'?'[data-checkout]':'#marketCheckoutForm button[type=submit]');if(button)button.disabled=!!out.unavailable;return out}catch(e){if(id!==quoteSequence||!$(target))return;$(target).innerHTML='<p class="market-alert">'+safe(e.message)+'</p>';const button=overlay.querySelector(target==='marketCartQuote'?'[data-checkout]':'#marketCheckoutForm button[type=submit]');if(button)button.disabled=true}}
async function checkout(){let a=cartLines();if(!a.length)return;openSheet('Order and payment','<p class="market-note">Choose a payment method after reviewing the products in your cart. No payment is marked complete until RANOVA verifies it.</p><form id="marketCheckoutForm"><label>Full name<input name="customer_name" required autocomplete="name"></label><label>Phone number<input name="customer_phone" type="tel" required autocomplete="tel"></label><label>Email (optional)<input name="customer_email" type="email" autocomplete="email"></label><label>Delivery country<select name="buyer_country_code" required><option value="GH">Ghana</option><option value="NG">Nigeria</option></select></label><label>Delivery location<input name="delivery_location" required placeholder="City, area and address"></label><div id="marketCheckoutQuote" class="market-quote">Checking store prices…</div><label>Payment method<select name="payment_method" required><option value="Mobile Money">Mobile Money</option><option value="Bank Transfer">Bank Transfer</option></select></label><label>Order note (optional)<textarea name="buyer_note" rows="2"></textarea></label><p class="market-note">Product prices and delivery charges may need confirmation. Payment instructions appear in your order tracking flow after you place the order.</p><div id="marketCheckoutMessage" role="status"></div><button class="market-primary" type="submit" disabled>Confirm order request</button></form>');updateQuote('GH','marketCheckoutQuote');let u=await db.auth.getUser().catch(()=>({data:{user:null}}));if(u.data?.user){let f=$('marketCheckoutForm');f.elements.customer_email.value=u.data.user.email||''}}
async function submit(form){let a=cartLines(),f=new FormData(form),msg=$('marketCheckoutMessage'),button=form.querySelector('button[type=submit]');let country=String(f.get('buyer_country_code'));button.disabled=true;button.textContent='Placing order…';try{const fresh=await getQuote(country);if(fresh.unavailable)throw Error('One of the selected seller products is no longer available. Please update your cart.');const {data:{session:s}}=await db.auth.getSession();lastOrderPhone=String(f.get('customer_phone')||'');const body={customer_name:f.get('customer_name'),customer_phone:f.get('customer_phone'),customer_email:f.get('customer_email'),buyer_country_code:country,buyer_country_name:country==='GH'?'Ghana':'Nigeria',delivery_location:f.get('delivery_location'),payment_method:f.get('payment_method'),buyer_note:f.get('buyer_note'),items:a.map(({p,q})=>p.kind==='seller'?{seller_product_id:p.id,quantity:q}:{product_id:p.id,product_name:p.name,quantity:q})};const res=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-place-order',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1','apikey':cfg.supabasePublishableKey,...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify(body)});const out=await res.json();if(!res.ok||!out.ok)throw Error(out.error||'Could not place the order.');cart={};persist();if(out.buyer_access_code&&out.order_ref)try{localStorage.setItem('ranova_buyer_code_'+out.order_ref,out.buyer_access_code)}catch{}openSheet('Order received','<p>Your order reference is <b>'+safe(out.order_ref)+'</b>.</p><p class="market-note">Save your reference and access code. Payment instructions and order updates are available in tracking.</p><p>Access code: <b>'+safe(out.buyer_access_code||'')+'</b></p><button class="market-primary" data-track-ref="'+safe(out.order_ref)+'">Track this order</button>')}catch(e){msg.innerHTML='<p class="market-alert">'+safe(e.message)+'</p>';button.disabled=false;button.textContent='Confirm order request'}}
function track(ref=''){
 openSheet('Track your order','<form id="marketTrackForm"><label>Order reference<input name="order_ref" required placeholder="RPE-…" value="'+safe(ref)+'"></label><label>Phone number used at checkout<input name="phone" type="tel" required value="'+safe(lastOrderPhone)+'"></label><div id="marketTrackResult" role="status"></div><button class="market-primary" type="submit">Check order status</button></form>');
}
async function lookup(form){const data=new FormData(form),result=$('marketTrackResult'),button=form.querySelector('button');button.disabled=true;result.textContent='Checking order…';try{const {data:{session:s}}=await db.auth.getSession();const r=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-order-status',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1','apikey':cfg.supabasePublishableKey,...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify({action:'lookup',order_ref:data.get('order_ref'),phone:data.get('phone')})});const out=await r.json();if(!r.ok||!out.ok)throw Error(out.error||'Could not find this order.');let o=out.order;result.innerHTML='<div class="market-detail-row"><b>'+safe(o.order_ref)+'</b><small>'+safe(String(o.status||'').replaceAll('_',' '))+' · Payment: '+safe(String(o.payment_status||'').replaceAll('_',' '))+'</small></div>'+((out.seller_orders||[]).map(x=>'<div class="market-detail-row"><b>'+safe(x.store_name)+'</b><small>'+safe(String(x.order_status||'').replaceAll('_',' '))+' · '+safe(x.order_ref)+'</small></div>').join(''))+'<div class="market-detail-row"><b>Product total</b><small>'+safe(money(o.product_total))+'</small></div><div class="market-detail-row"><b>Delivery</b><small>'+safe(money(o.delivery_fee))+'</small></div>'+(out.payment_instructions?'<div class="market-alert"><b>Payment instructions</b><br>'+safe(out.payment_instructions.instructions||'')+'<br>'+safe(out.payment_instructions.provider_name||'')+' '+safe(out.payment_instructions.account_name||'')+' '+safe(out.payment_instructions.account_reference||'')+'</div>':'<p class="market-note">Payment details appear only when they are available for this order.</p>')}
 catch(e){result.innerHTML='<p class="market-alert">'+safe(e.message)+'</p>'}finally{button.disabled=false}}
function account(){if(window.RPE_ACCOUNT_OPEN)window.RPE_ACCOUNT_OPEN();else location.hash='account'}
function home(){storeId='';category='';query='';shown=BATCH;$('marketSearch').value='';render();window.scrollTo(0,0)}
function show(){root.classList.remove('hide');window.scrollTo(0,0)}
window.RPE_OPEN_MARKET=()=>{document.getElementById('auth').classList.add('hide');document.getElementById('app').classList.add('hide');document.getElementById('setup').classList.add('hide');show()};
root.addEventListener('click',e=>{let b=e.target.closest('[data-product],[data-add],[data-store],[data-category],[data-back],[data-compare],[data-open-compare],[data-clear-compare]');if(!b)return;if(b.dataset.product)product(b.dataset.product);else if(b.dataset.add)add(b.dataset.add);else if(b.dataset.compare)toggleCompare(b.dataset.compare);else if(b.dataset.openCompare!==undefined)showCompare();else if(b.dataset.clearCompare!==undefined){compareIds=[];render()}else if(b.dataset.store){storeId=b.dataset.store;category='';query='';shown=BATCH;render();window.scrollTo(0,0)}else if(b.dataset.category!==undefined){storeId='';category=b.dataset.category;shown=BATCH;render()}else if(b.dataset.back!==undefined)home()});
overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('[data-close]')){closeSheet();return}let b=e.target.closest('[data-product],[data-add],[data-store],[data-quantity],[data-remove],[data-checkout],[data-track-ref]');if(!b)return;if(b.dataset.product)product(b.dataset.product);else if(b.dataset.add)add(b.dataset.add);else if(b.dataset.store){closeSheet();storeId=b.dataset.store;category='';query='';render()}else if(b.dataset.quantity){let p=items.find(x=>String(x.id)===b.dataset.quantity);if(!p)return;cart[p.id]=Math.max(Number(p.moq||1),Number(cart[p.id])+Number(b.dataset.step));if(p.stock_quantity!=null)cart[p.id]=Math.min(cart[p.id],Number(p.stock_quantity));persist();showCart()}else if(b.dataset.remove){delete cart[b.dataset.remove];persist();showCart()}else if(b.dataset.checkout!==undefined)checkout();else if(b.dataset.trackRef)track(b.dataset.trackRef)});
overlay.addEventListener('change',e=>{if(e.target.name==='buyer_country_code')updateQuote(e.target.value,'marketCheckoutQuote')});overlay.addEventListener('submit',e=>{if(e.target.id==='marketCheckoutForm'){e.preventDefault();submit(e.target)}else if(e.target.id==='marketTrackForm'){e.preventDefault();lookup(e.target)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});
$('marketSearchForm').addEventListener('submit',e=>{e.preventDefault();query=$('marketSearch').value.trim();category='';storeId='';shown=BATCH;render()});$('marketSearch').addEventListener('input',e=>{query=e.target.value.trim();category='';storeId='';shown=BATCH;render()});
$('marketSort').addEventListener('change',e=>{sortMode=e.target.value;shown=BATCH;render()});$('marketMinimum').addEventListener('change',e=>{maxMinimum=Number(e.target.value)||0;shown=BATCH;render()});$('marketPriced').addEventListener('change',e=>{pricedOnly=e.target.checked;shown=BATCH;render()});
$('marketTrack').onclick=()=>track();$('marketRefresh').onclick=()=>{nonce++;if(!loading)load()};$('marketMore').onclick=()=>{shown+=BATCH;render()};$('marketHome').onclick=home;$('marketBrowse').onclick=()=>{$('marketCategories').scrollIntoView({behavior:'smooth'})};$('marketCart').onclick=showCart;$('marketMe').onclick=$('marketAccount').onclick=account;updateCount();load();setInterval(()=>{if(!document.hidden&&!query&&!storeId&&!category){nonce++;render()}},600000);
})();
