(()=>{
'use strict';
const cfg=window.RPE_CONFIG||{},root=document.getElementById('marketApp'),overlay=document.getElementById('marketOverlay');
const $=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=cfg.supabaseUrl&&cfg.supabasePublishableKey&&window.supabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
window.RPE_SUPABASE=db;
const KEY='ranova_market_cart_v2',DEVICE='ranova_market_device_v1',BATCH=24;
let lastOrderPhone='',items=[],stores=new Map(),cart={},shown=BATCH,category='',query='',storeId='',nonce=0,loading=false,session=null;
try{cart=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{cart={}}
let device='';try{device=localStorage.getItem(DEVICE)||crypto.randomUUID();localStorage.setItem(DEVICE,device)}catch{device=String(Math.random())}
const money=(v,c='GHS')=>v==null?'Ask for price':new Intl.NumberFormat('en-GH',{style:'currency',currency:c||'GHS'}).format(Number(v));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const img=p=>p.image||'';
const available=p=>p.stock_status!=='out_of_stock'&&(p.stock_quantity==null||Number(p.stock_quantity)>0);
const seed=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
function shuffle(a,s){let arr=[...a],v=seed(s);for(let i=arr.length-1;i>0;i--){v+=0x6d2b79f5;let t=v;t=Math.imul(t^t>>>15,1|t);t^=t+Math.imul(t^t>>>7,61|t);let j=Math.floor(((t^t>>>14)>>>0)/4294967296*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function fairOrder(a){let buckets=new Map(),ordered=[];for(const p of shuffle(a,device+'|'+Math.floor(Date.now()/600000)+'|'+nonce)){if(!buckets.has(p.store_id))buckets.set(p.store_id,[]);buckets.get(p.store_id).push(p)}let keys=shuffle([...buckets.keys()],device+'|stores|'+nonce);while(keys.length){let next=[];for(const k of keys){let b=buckets.get(k);ordered.push(b.shift());if(b.length)next.push(k)}keys=shuffle(next,device+'|round|'+ordered.length)}return ordered}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(cart))}catch{}updateCount()}
function updateCount(){let n=Object.values(cart).reduce((s,q)=>s+Number(q||0),0);$('marketCartCount').textContent=n||''}
function note(t){$('marketGrid').innerHTML='<p class="market-state">'+safe(t)+'</p>'}
function canonical(rows){const seen=new Set();return rows.filter(p=>{let key=p.store_id+'|'+norm(p.name);if(seen.has(key))return false;seen.add(key);return true})}
async function load(){if(!db){note('The product catalogue is temporarily unavailable.');return}loading=true;note('Loading products from RANOVA stores…');try{
 const [sellers,sp,core]=await Promise.all([
 db.from('ranova_seller_stores').select('id,store_name,slug,tagline,description,logo_url,business_location,fulfilment_summary,return_policy_summary').eq('store_status','active').limit(500),
 db.from('ranova_seller_products').select('id,store_id,name,category,short_description,description,price,currency,moq,stock_quantity,stock_status,unit_label,primary_image_url,image_urls,created_at').eq('product_status','active').order('created_at',{ascending:false}).limit(1000),
 db.from('products').select('id,name,sku,legacy_id,short_description,description,price,currency,stock_quantity,stock_status,specifications,product_images(image_url,is_primary,sort_order),categories(name)').eq('active',true).limit(1000)
 ]);
 if(sellers.error||sp.error||core.error)throw new Error('Could not load the catalogue. Tap Refresh to try again.');
 stores=new Map((sellers.data||[]).map(s=>[s.id,s]));const prime={id:'ranova-prime',store_name:'Ranova Prime Enterprise',description:'Official RANOVA Prime catalogue',business_location:'Ghana'};stores.set(prime.id,prime);
 const seller=(sp.data||[]).filter(p=>stores.has(p.store_id)&&p.stock_status!=='out_of_stock').map(p=>({...p,kind:'seller',image:p.primary_image_url||p.image_urls?.[0]||'',store_name:stores.get(p.store_id).store_name,images:[p.primary_image_url,...(p.image_urls||[])].filter(Boolean)}));
 const known=new Set(seller.filter(p=>/ranova prime/i.test(p.store_name)).map(p=>norm(p.name)));
 const legacy=(core.data||[]).filter(p=>p.stock_status!=='out_of_stock'&&!known.has(norm(p.name))).map(p=>{let images=(p.product_images||[]).slice().sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||(a.sort_order||0)-(b.sort_order||0)).map(x=>x.image_url);return {...p,store_id:prime.id,store_name:prime.store_name,kind:'prime',category:p.categories?.name||'Other',moq:1,image:images[0]||'',images}});
 items=canonical([...seller,...legacy]);if(!items.length)note('No approved products are available yet. Check again shortly.');else render();
 }catch(e){note(e.message||'Could not load products. Tap Refresh to retry.')}finally{loading=false}}
function filtered(){let a=items;if(storeId)a=a.filter(p=>p.store_id===storeId);if(category)a=a.filter(p=>p.category===category);if(query){const q=norm(query);a=a.filter(p=>norm([p.name,p.category,p.description,p.short_description,p.store_name].join(' ')).includes(q))}return query||category||storeId?a:fairOrder(a)}
function card(p){let disabled=!available(p),picture=img(p)?'<img src="'+safe(img(p))+'" alt="'+safe(p.name)+'" loading="lazy">':'<span class="market-state">Image unavailable</span>';return '<article class="market-card"><button class="market-image" data-product="'+safe(p.id)+'" aria-label="View '+safe(p.name)+'">'+picture+'</button><div class="market-card-body"><button class="market-store-link" data-store="'+safe(p.store_id)+'">'+safe(p.store_name)+'</button><button class="market-name" data-product="'+safe(p.id)+'">'+safe(p.name)+'</button><div class="market-meta">'+safe(p.category||'Product')+(Number(p.moq)>1?' · Min '+Number(p.moq):'')+'</div><div class="market-price">'+safe(money(p.price,p.currency))+'</div></div><button class="market-add" data-add="'+safe(p.id)+'" '+(disabled?'disabled':'')+'>'+(disabled?'Unavailable':'Add to cart')+'</button></article>'}
function render(){const a=filtered();$('marketHeading').textContent=storeId?(stores.get(storeId)?.store_name||'Store'):query?('Results for “'+query+'”'):category||'Discover products';$('marketGrid').innerHTML=a.length?a.slice(0,shown).map(card).join(''):'<p class="market-state">No products match your search. Try a different category or search term.</p>';$('marketMore').classList.toggle('hide',a.length<=shown);const cats=[...new Set(items.map(p=>p.category).filter(Boolean))].sort();$('marketCategories').innerHTML=['All',...cats].map(c=>'<button type="button" data-category="'+safe(c==='All'?'':c)+'" class="'+(category===(c==='All'?'':c)?'selected':'')+'">'+safe(c)+'</button>').join('');$('marketStoreView').classList.toggle('hide',!storeId);if(storeId){const s=stores.get(storeId);$('marketStoreView').innerHTML='<button class="market-back" data-back>← All stores</button><div class="market-store-head">'+(s?.logo_url?'<img src="'+safe(s.logo_url)+'" alt="">':'')+'<div><h1>'+safe(s?.store_name||'Store')+'</h1><p>'+safe(s?.business_location||'')+'</p></div></div><p>'+safe(s?.description||s?.tagline||'Browse this store’s products.')+'</p>'+(s?.fulfilment_summary?'<p><b>Delivery:</b> '+safe(s.fulfilment_summary)+'</p>':'')}}
function openSheet(title,body){overlay.innerHTML='<div class="market-sheet"><div class="market-sheet-head"><h2>'+safe(title)+'</h2><button type="button" data-close aria-label="Close">×</button></div>'+body+'</div>';overlay.classList.remove('hide');document.body.style.overflow='hidden'}
function closeSheet(){overlay.classList.add('hide');overlay.innerHTML='';document.body.style.overflow=''}
function product(id){const p=items.find(x=>x.id===id);if(!p)return;let images=[...new Set(p.images||[])];openSheet(p.name,'<div class="market-gallery">'+(images.length?images.map(x=>'<img src="'+safe(x)+'" alt="'+safe(p.name)+'">').join(''):'<p>Image unavailable</p>')+'</div><h3>'+safe(p.name)+'</h3><button class="market-store-link" data-store="'+safe(p.store_id)+'">Sold by '+safe(p.store_name)+'</button><div class="market-detail-row"><b>'+safe(money(p.price,p.currency))+'</b><small>Minimum order: '+Number(p.moq||1)+' · '+safe(p.stock_status?.replaceAll('_',' ')||'Confirm availability')+'</small></div><p class="market-description">'+safe(p.description||p.short_description||'Ask the seller for more details before ordering.')+'</p>'+(p.specifications?Object.entries(p.specifications).map(([k,v])=>'<div class="market-detail-row"><b>'+safe(k.replaceAll('_',' '))+'</b><small>'+safe(typeof v==='object'?JSON.stringify(v):v)+'</small></div>').join(''):'')+'<button class="market-primary" data-add="'+safe(p.id)+'" '+(!available(p)?'disabled':'')+'>'+(available(p)?'Add to cart':'Unavailable')+'</button>')}
function add(id){let p=items.find(x=>x.id===id);if(!p||!available(p))return;cart[id]=Math.max(Number(p.moq||1),Number(cart[id]||0)+1);persist();showCart()}
function cartLines(){let valid=Object.entries(cart).map(([id,q])=>({p:items.find(x=>x.id===id),q:Number(q)})).filter(x=>x.p&&x.q>0);return valid}
function showCart(){let a=cartLines();openSheet('Your cart',a.length?a.map(({p,q})=>'<div class="market-cart-row">'+(p.image?'<img src="'+safe(p.image)+'" alt="">':'<span></span>')+'<div><b>'+safe(p.name)+'</b><small>'+safe(p.store_name)+' · '+safe(money(p.price,p.currency))+'</small><div class="market-qty"><button data-quantity="'+safe(p.id)+'" data-step="-1" aria-label="Decrease quantity">−</button><span>'+q+'</span><button data-quantity="'+safe(p.id)+'" data-step="1" aria-label="Increase quantity">+</button></div></div><button class="market-remove" data-remove="'+safe(p.id)+'">Remove</button></div>').join('')+'<p class="market-note">Items from different stores can be ordered together. Delivery and any unconfirmed prices are reviewed before payment.</p><button class="market-primary" data-checkout>Place order</button>':'<p class="market-note">Your cart is empty. Browse products and add the ones you want.</p>')}
async function checkout(){let a=cartLines();if(!a.length)return;openSheet('Order and payment','<p class="market-note">Choose a payment method after reviewing the products in your cart. No payment is marked complete until RANOVA verifies it.</p><form id="marketCheckoutForm"><label>Full name<input name="customer_name" required autocomplete="name"></label><label>Phone number<input name="customer_phone" type="tel" required autocomplete="tel"></label><label>Email (optional)<input name="customer_email" type="email" autocomplete="email"></label><label>Delivery country<select name="buyer_country_code" required><option value="GH">Ghana</option><option value="NG">Nigeria</option><option value="other">Other country</option></select></label><label>Country name (if other)<input name="other_country" placeholder="Country name"></label><label>Delivery location<input name="delivery_location" required placeholder="City, area and address"></label><label>Payment method<select name="payment_method" required><option value="Mobile Money">Mobile Money</option><option value="Bank Transfer">Bank Transfer</option></select></label><label>Order note (optional)<textarea name="buyer_note" rows="2"></textarea></label><p class="market-note">Product prices and delivery charges may need confirmation. Payment instructions appear in your order tracking flow after you place the order.</p><div id="marketCheckoutMessage" role="status"></div><button class="market-primary" type="submit">Confirm order request</button></form>');let u=await db.auth.getUser().catch(()=>({data:{user:null}}));if(u.data?.user){let f=$('marketCheckoutForm');f.elements.customer_email.value=u.data.user.email||''}}
async function submit(form){let a=cartLines(),f=new FormData(form),msg=$('marketCheckoutMessage'),button=form.querySelector('button[type=submit]');let country=String(f.get('buyer_country_code'));if(country==='other'){msg.innerHTML='<p class="market-alert">Please choose a supported delivery country. Contact RANOVA for other destinations.</p>';return}button.disabled=true;button.textContent='Placing order…';try{const {data:{session:s}}=await db.auth.getSession();lastOrderPhone=String(f.get('customer_phone')||'');const body={customer_name:f.get('customer_name'),customer_phone:f.get('customer_phone'),customer_email:f.get('customer_email'),buyer_country_code:country,buyer_country_name:country==='GH'?'Ghana':'Nigeria',delivery_location:f.get('delivery_location'),payment_method:f.get('payment_method'),buyer_note:f.get('buyer_note'),items:a.map(({p,q})=>p.kind==='seller'?{seller_product_id:p.id,quantity:q}:{product_id:p.id,product_name:p.name,quantity:q})};const res=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-place-order',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1','apikey':cfg.supabasePublishableKey,...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify(body)});const out=await res.json();if(!res.ok||!out.ok)throw Error(out.error||'Could not place the order.');cart={};persist();if(out.buyer_access_code&&out.order_ref)try{localStorage.setItem('ranova_buyer_code_'+out.order_ref,out.buyer_access_code)}catch{}openSheet('Order received','<p>Your order reference is <b>'+safe(out.order_ref)+'</b>.</p><p class="market-note">Save your reference and access code. Payment instructions and order updates are available in tracking.</p><p>Access code: <b>'+safe(out.buyer_access_code||'')+'</b></p><button class="market-primary" data-track-ref="'+safe(out.order_ref)+'">Track this order</button>')}catch(e){msg.innerHTML='<p class="market-alert">'+safe(e.message)+'</p>';button.disabled=false;button.textContent='Confirm order request'}}
function track(ref=''){
 openSheet('Track your order','<form id="marketTrackForm"><label>Order reference<input name="order_ref" required placeholder="RPE-…" value="'+safe(ref)+'"></label><label>Phone number used at checkout<input name="phone" type="tel" required value="'+safe(lastOrderPhone)+'"></label><div id="marketTrackResult" role="status"></div><button class="market-primary" type="submit">Check order status</button></form>');
}
async function lookup(form){const data=new FormData(form),result=$('marketTrackResult'),button=form.querySelector('button');button.disabled=true;result.textContent='Checking order…';try{const {data:{session:s}}=await db.auth.getSession();const r=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-order-status',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1','apikey':cfg.supabasePublishableKey,...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify({action:'lookup',order_ref:data.get('order_ref'),phone:data.get('phone')})});const out=await r.json();if(!r.ok||!out.ok)throw Error(out.error||'Could not find this order.');let o=out.order;result.innerHTML='<div class="market-detail-row"><b>'+safe(o.order_ref)+'</b><small>'+safe(String(o.status||'').replaceAll('_',' '))+' · Payment: '+safe(String(o.payment_status||'').replaceAll('_',' '))+'</small></div>'+((out.seller_orders||[]).map(x=>'<div class="market-detail-row"><b>'+safe(x.store_name)+'</b><small>'+safe(String(x.order_status||'').replaceAll('_',' '))+' · '+safe(x.order_ref)+'</small></div>').join(''))+'<div class="market-detail-row"><b>Product total</b><small>'+safe(money(o.product_total))+'</small></div><div class="market-detail-row"><b>Delivery</b><small>'+safe(money(o.delivery_fee))+'</small></div>'+(out.payment_instructions?'<div class="market-alert"><b>Payment instructions</b><br>'+safe(out.payment_instructions.instructions||'')+'<br>'+safe(out.payment_instructions.provider_name||'')+' '+safe(out.payment_instructions.account_name||'')+' '+safe(out.payment_instructions.account_reference||'')+'</div>':'<p class="market-note">Payment details appear only when they are available for this order.</p>')}
 catch(e){result.innerHTML='<p class="market-alert">'+safe(e.message)+'</p>'}finally{button.disabled=false}}
function account(){if(window.RPE_ACCOUNT_OPEN)window.RPE_ACCOUNT_OPEN();else location.hash='account'}
function home(){storeId='';category='';query='';shown=BATCH;$('marketSearch').value='';render();window.scrollTo(0,0)}
function show(){root.classList.remove('hide');window.scrollTo(0,0)}
window.RPE_OPEN_MARKET=()=>{document.getElementById('auth').classList.add('hide');document.getElementById('app').classList.add('hide');document.getElementById('setup').classList.add('hide');show()};
root.addEventListener('click',e=>{let b=e.target.closest('[data-product],[data-add],[data-store],[data-category],[data-back]');if(!b)return;if(b.dataset.product)product(b.dataset.product);else if(b.dataset.add)add(b.dataset.add);else if(b.dataset.store){storeId=b.dataset.store;category='';query='';shown=BATCH;render();window.scrollTo(0,0)}else if(b.dataset.category!==undefined){storeId='';category=b.dataset.category;shown=BATCH;render()}else if(b.dataset.back!==undefined)home()});
overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('[data-close]'))closeSheet();let b=e.target.closest('[data-add],[data-store],[data-quantity],[data-remove],[data-checkout],[data-track-ref]');if(!b)return;if(b.dataset.add)add(b.dataset.add);else if(b.dataset.store){closeSheet();storeId=b.dataset.store;category='';query='';render()}else if(b.dataset.quantity){let p=items.find(x=>x.id===b.dataset.quantity);cart[p.id]=Math.max(p.moq||1,Number(cart[p.id])+Number(b.dataset.step));persist();showCart()}else if(b.dataset.remove){delete cart[b.dataset.remove];persist();showCart()}else if(b.dataset.checkout!==undefined)checkout();else if(b.dataset.trackRef)track(b.dataset.trackRef)});
overlay.addEventListener('submit',e=>{if(e.target.id==='marketCheckoutForm'){e.preventDefault();submit(e.target)}else if(e.target.id==='marketTrackForm'){e.preventDefault();lookup(e.target)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});
$('marketSearchForm').addEventListener('submit',e=>{e.preventDefault();query=$('marketSearch').value.trim();category='';storeId='';shown=BATCH;render()});$('marketSearch').addEventListener('input',e=>{query=e.target.value.trim();category='';storeId='';shown=BATCH;render()});
$('marketTrack').onclick=()=>track();$('marketRefresh').onclick=()=>{nonce++;if(!loading)load()};$('marketMore').onclick=()=>{shown+=BATCH;render()};$('marketHome').onclick=home;$('marketBrowse').onclick=()=>{$('marketCategories').scrollIntoView({behavior:'smooth'})};$('marketCart').onclick=showCart;$('marketMe').onclick=$('marketAccount').onclick=account;updateCount();load();setInterval(()=>{if(!document.hidden&&!query&&!storeId&&!category){nonce++;render()}},600000);
})();
