(()=>{'use strict';
const authReturn=location.hash.includes('access_token=')||new URLSearchParams(location.search).has('code');
const $=id=>document.getElementById(id),cfg=window.RPE_CONFIG||{},sb=window.supabase&&cfg.supabaseUrl?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
const paths={user:'M20 21a8 8 0 0 0-16 0 M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3 M8 12l3 3 5-6',store:'M4 10v11h16V10 M3 3h18l-2 7H5L3 3 M9 21v-7h6v7',home:'m3 10 9-7 9 7 M5 9v12h14V9 M9 21v-7h6v7',message:'M21 4H3v14h5l-5 4V4 M7 8h10 M7 12h7',cart:'M2 3h3l3 13h11l2-9H6 M10 20h.01 M18 20h.01',back:'m15 5-7 7 7 7',switch:'M4 7h16l-4-4 M20 17H4l4 4',gift:'M3 8h18v4H3z M5 12v9h14v-9 M12 8v13 M12 8C3 8 5 0 9 4l3 4 M12 8c9 0 7-8 3-4l-3 4',box:'m12 3 9 5-9 5-9-5 9-5 M3 8v10l9 4 9-4V8 M12 13v9 M7 6l10 5',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0 M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',chart:'M4 3v18h17 M8 16v-5 M13 16V8 M18 16V5',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3',factory:'M3 21V10l6 3V7l6 4V3h5v18H3 M7 17h1 M12 17h1 M17 17h1'};
const svg=k=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[k]+'"/></svg>';
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));
const benefits=[['gift','Growth support','Help your store grow','Planned','The reference advertises signup business credits. RANOVA has not launched a credit or cash-reward programme.'],['box','Quick publishing','List your products','After approval','Approved sellers can add products and submit a catalogue through the Seller Dashboard. Listings require RANOVA review.'],['pin','Map visibility','Help buyers find you','Planned','Map-based store discovery is planned. Business location is collected during registration.'],['message','Buyer inquiries','Keep conversations together','After approval','Buyers can contact your store through RANOVA’s existing messaging service once your approved store is published.'],['chart','Industry insights','Understand your market','Planned','Industry trend reports are not yet available in RANOVA.'],['shield','Business verification','Build buyer confidence','RANOVA review','RANOVA reviews your submitted business documents before approving your store. This is not Sesame Credit certification.'],['spark','AI assistant','Support daily tasks','Planned','An AI business assistant is not yet available. Registration does not include an AI service subscription.'],['factory','Source credentials','Show business evidence','Document review','Submit genuine supplier and business documents during verification. RANOVA does not award manufacturer status without supporting evidence.']];
$('benefitGrid').innerHTML=benefits.map((b,i)=>'<button type="button" class="benefit" data-benefit="'+i+'"><span class="benefit-icon">'+svg(b[0])+'</span><b>'+b[1]+'</b><small>'+b[2]+'</small><span class="badge">'+b[3]+'</span></button>').join('');
$('benefitGrid').onclick=e=>{const b=e.target.closest('[data-benefit]');if(!b)return;const x=benefits[Number(b.dataset.benefit)];$('benefitContent').innerHTML='<span class="benefit-icon">'+svg(x[0])+'</span><h2>'+x[1]+'</h2><p>'+x[4]+'</p>';$('benefitDialog').showModal()};$('closeBenefit').onclick=$('dismissBenefit').onclick=()=>$('benefitDialog').close();
function route(){const register=location.hash==='#register';$('welcome').hidden=register;$('registration').hidden=!register;window.scrollTo(0,0)}document.querySelectorAll('[data-register]').forEach(b=>b.onclick=()=>{location.hash='register'});$('back').onclick=()=>{location.hash=''};window.addEventListener('hashchange',route);route();
let destination=null,verified=false,busy=false,pendingRef=null;
function method(){return document.querySelector('[name=method]:checked').value}
function phone(){const n=$('phone').value.replace(/[\s()-]/g,'');return $('dial').value==='other'?n:$('dial').value+n.replace(/^0+/,'')}
function details(){return {member:$('member').value.trim(),company:$('company').value.trim(),phone:phone(),email:$('email').value.trim()}}
function showBusiness(){verified=true;$('registerForm').hidden=true;$('businessStep').hidden=false;location.hash='register';$('businessStep').scrollIntoView({behavior:'smooth',block:'center'})}
function err(e){return e?.message||'Please try again.'}
document.querySelectorAll('[name=method]').forEach(el=>el.onchange=()=>{const email=method()==='email';$('emailField').hidden=!email;$('email').required=email;destination=null;$('code').value='';$('codeHelp').textContent=email?'Your email may contain a code or a sign-in link. Use either to continue.':'A text message will be sent if SMS verification is available for your number.'});
$('sendCode').onclick=async()=>{if(busy)return;const d=details(),m=method();if(!d.member||!d.company||!/^\+[1-9]\d{7,14}$/.test(d.phone)||(m==='email'&&!$('email').checkValidity())){$('formStatus').textContent='Enter your name, company and a valid phone number'+(m==='email'?' and email address.':'.');return}if(!$('consent').checked){$('formStatus').textContent='Please read and accept the terms and privacy policy first.';return}busy=true;$('sendCode').disabled=true;try{if(!sb)throw Error('Registration is temporarily unavailable.');const metadata={full_name:d.member,business_name:d.company,contact_phone:d.phone};const request=m==='email'?{email:d.email,options:{emailRedirectTo:new URL('./seller-start.html#register',location.href).href,data:metadata}}:{phone:d.phone,options:{data:metadata}};const {error}=await sb.auth.signInWithOtp(request);if(error)throw error;destination={method:m,value:m==='email'?d.email:d.phone};$('formStatus').textContent=m==='email'?'Check your email for a verification code or sign-in link.':'A verification code has been sent to your phone.'}catch(e){$('formStatus').textContent=err(e)+(m==='phone'?' You can select email verification instead.':'')}finally{busy=false;$('sendCode').disabled=false}};
$('registerForm').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!destination){$('formStatus').textContent='Send a verification code first.';return}const d=details();if(destination.method!==method()||destination.value!==(method()==='email'?d.email:d.phone)){$('formStatus').textContent='Your contact details changed. Request a new code.';return}busy=true;$('registerButton').disabled=true;try{const req=destination.method==='email'?{email:destination.value,token:$('code').value.trim(),type:'email'}:{phone:destination.value,token:$('code').value.trim(),type:'sms'};const {error}=await sb.auth.verifyOtp(req);if(error)throw error;const updated=await sb.auth.updateUser({data:{full_name:d.member,business_name:d.company,contact_phone:d.phone}});if(updated.error)throw updated.error;showBusiness()}catch(e){$('formStatus').textContent=err(e)}finally{busy=false;$('registerButton').disabled=false}};
$('businessForm').onsubmit=async e=>{e.preventDefault();if(!verified||busy)return;busy=true;const button=e.target.querySelector('button');button.disabled=true;try{const d=details();const {data:{session}}=await sb.auth.getSession();if(!session)throw Error('Please sign in again before continuing.');const saved=JSON.parse(sessionStorage.getItem('ranova_new_seller_application')||'null');if(saved?.user===session.user.id&&saved.phone===d.phone)pendingRef=saved.ref;if(!pendingRef){const response=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-seller-apply',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1'},body:JSON.stringify({business_name:d.company,contact_person:d.member,phone:d.phone,email:session.user.email||d.email,business_location:$('location').value.trim(),supplier_type:$('type').value,categories:$('categories').value.trim()})});const out=await response.json();if(!response.ok||!out.ok)throw Error(out.error||'Could not save your application.');pendingRef=out.application_ref;sessionStorage.setItem('ranova_new_seller_application',JSON.stringify({user:session.user.id,phone:d.phone,ref:pendingRef}));sessionStorage.setItem('ranovaSellerApplicationRef',pendingRef);sessionStorage.setItem('ranovaSellerApplicationPhone',d.phone);sessionStorage.setItem('ranovaSellerApplicationEmail',session.user.email||d.email)}const linked=await fetch(cfg.supabaseUrl+'/functions/v1/ranova-seller-link',{method:'POST',headers:{'Content-Type':'application/json','x-ranova-client':'ranova-site-v1',apikey:cfg.supabasePublishableKey,Authorization:'Bearer '+session.access_token},body:JSON.stringify({application_ref:pendingRef,phone:d.phone})});const result=await linked.json();if(!linked.ok||!result.ok)throw Error(result.error||'Application saved. Please try again to connect your account.');location.href='../all/seller-center.html?ref='+encodeURIComponent(pendingRef)}catch(e){$('businessStatus').textContent=err(e)}finally{busy=false;button.disabled=false}};
if(sb)sb.auth.getSession().then(({data})=>{const user=data.session?.user;if(!user)return;const m=user.user_metadata||{};$('member').value=m.full_name||'';$('company').value=m.business_name||'';$('email').value=user.email||'';if(m.contact_phone){$('dial').value='other';$('phone').value=m.contact_phone}if(m.full_name&&m.business_name&&m.contact_phone){verified=true;$('registerForm').hidden=true;$('businessStep').hidden=false;if(authReturn||location.hash==='#register')showBusiness()}});
})();
