plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ranova.marketplace'
    compileSdk 35

    defaultConfig {
        applicationId "com.ranova.marketplace"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "1.0.3"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
